CREATE VIEW [dbo].[vw_JournalDetails]
AS
SELECT
    j.[JournalId],
    j.[JournalName],
    j.[JournalDoi],
    j.[JournalSeoName],
    j.[JournalAcceptanceRate],
    j.[JournalDecision],
    j.[JournalAcceptancePublic],
    j.[JournalCitescore1],
    j.[JournalImpact],
    j.[JournalApc],
    j.[JournalSnip],
    j.[JournalSjr],
    j.[JournalCitescore],
    j.[Volume],
    j.[Issue],
    j.[Year],
    j.[Email],
    j.[Scholar],
    j.[IndexedArticle],
    j.[IndexingImage],
    j.[IndexingUrl],
    j.[ImpactFactor],
    j.[CrossrefUrl],
    j.[CrossrefImage],
    j.[IssnNumber],
    j.[YoutubeLink],
    j.[CallForPapers],
    j.[AimsAndScope],
    j.[ChiefEditor],
    j.[JournalImage],
    j.[IsExternalJournal],
    j.[JournalStatus],
    j.[JournalCreatedDate],
    j.[JournalUpdatedDate],
    e.[EditorName]          AS [ChiefEditorName],
    e.[EditorAddress]       AS [ChiefEditorAddress],
    e.[EditorDesignation],
    e.[Qualification],
    e.[ProfileImage]        AS [EditorProfileImage],
    e.[EditorPhone],
    e.[EditorEmail],
    e.[EditorOrcid],
    e.[EditorGoogleScholar],
    e.[EditorWebsite],
    e.[EditorBiography]     AS [Biography],
    e.[EditorResearch]      AS [Research]
FROM [dbo].[Journals] j
LEFT JOIN [dbo].[Editors] e ON j.[ChiefEditor] = e.[EditorId];
GO
